In [2]:
import pandas as pd

In [3]:
channel_8_1 = pd.read_excel("./../data/data_wuhan/stress_and_CV_experiment_8_Channel_8.1.xlsx", sheet_name="Channel_8_1")
channel_8_2 = pd.read_excel("./../data/data_wuhan/stress_and_CV_experiment_8_Channel_8.2.xlsx", sheet_name="Channel_8_1")
channel_8_3 = pd.read_excel("./../data/data_wuhan/stress_and_CV_experiment_8_Channel_8.3.xlsx", sheet_name="Channel_8_1")
channel_8_4 = pd.read_excel("./../data/data_wuhan/stress_and_CV_experiment_8_Channel_8.4.xlsx", sheet_name="Channel_8_1")

In [4]:
channel_8 = pd.concat([channel_8_1, channel_8_2, channel_8_3, channel_8_4], ignore_index=True)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [5]:
channel_8.head()

,ACR(Ohm),Aux_Temperature(℃)_1,Charge_Capacity(Ah),Charge_Energy(Wh),Current(A),Cycle_Index,Date_Time,Discharge_Capacity(Ah),Discharge_Energy(Wh),Internal Resistance(Ohm),Step_Index,Step_Time(s),Test_Time(s),Time,Unnamed: 2,Voltage(V),dV/dt(V/s)
0,NaN,24.715055,0.021561,0.075147,1.300117,1,2018-09-14 16:39:49.900,5.115762e-08,1.717971e-07,0.0,1,60.0066,60.0066,NaN,NaN,3.513011,0.000674
1,NaN,24.715055,0.043229,0.151618,1.300257,1,2018-09-14 16:40:49.896,5.115762e-08,1.717971e-07,0.0,1,120.0024,120.0024,NaN,NaN,3.540922,0.000282
2,NaN,24.639656,0.064904,0.228499,1.300373,1,2018-09-14 16:41:49.905,5.115762e-08,1.717971e-07,0.0,1,180.0115,180.0115,NaN,NaN,3.551687,0.000183
3,NaN,24.938622,0.086578,0.305552,1.300310,1,2018-09-14 16:42:49.897,5.115762e-08,1.717971e-07,0.0,1,240.0030,240.0030,NaN,NaN,3.558240,0.000133
4,NaN,24.904522,0.108247,0.382722,1.300228,1,2018-09-14 16:43:49.901,5.115762e-08,1.717971e-07,0.0,1,300.0079,300.0079,NaN,NaN,3.564484,0.000097

In [6]:
channel_8.to_csv("channel_8.csv", index=False)